export const GET_GAMES_LOADING = 'GET_GAMES_LOADING';
export const GET_GAMES_SUCCESS = 'GET_GAMES_SUCCESS';
export const GET_GAMES_FAIL = 'GET_GAMES_FAIL';
export const GET_SINGLE_GAME_LOADING = 'GET_SINGLE_GAME_LOADING';
export const GET_SINGLE_GAME_SUCCESS = 'GET_SINGLE_GAME_SUCCESS';
export const GET_SINGLE_GAME_FAIL = 'GET_SINGLE_GAME_FAIL';
